fix: disk metrics error
ClickHouse/clickhouse_exporter pull request #81
Opened 2023-07-03 10:00 UTC by fuxingZhang

fix issue https://github.com/ClickHouse/clickhouse_exporter/issues/80

clickhouse_free_space_in_gigabytes and clickhouse_total_space_in_gigabytes  are removed.
Because they can be calculated by free_space_in_bytes and total_space_in_bytes.

curl http://localhost:9116/metrics, you can see: 

![image](https://github.com/ClickHouse/clickhouse_exporter/assets/25921552/332538f6-9a7a-4720-b494-fe31ddf469ae)

![image](https://github.com/ClickHouse/clickhouse_exporter/assets/25921552/cc192653-2b84-4c16-a796-16b5da62ba1c)

2023-07-03 10:05 UTC, Slach requested changes

2023-07-03 10:07 UTC, Slach requested changes

2023-07-03 10:07 UTC, Slach commented on exporter/exporter.go
> +		}, []string{"name"}).WithLabelValues(dm.name)
instead of `name` better will `disk` label here

2023-07-03 10:07 UTC, Slach commented on exporter/exporter.go
> +		}, []string{"name"}).WithLabelValues(dm.name)
`disk` instead of `name` more mental

2023-07-03 10:35 UTC, fuxingZhang commented on exporter/exporter.go
> +			return nil, fmt.Errorf("parseKeyValueResponse: unexpected %d line: %s", i, line)
Thanks for the guidance, I have revised and resubmitted.

2023-07-03 10:36 UTC, fuxingZhang commented
Thanks for the guidance, I have revised and resubmitted.

2023-07-05 11:26 UTC, Slach approved these changes

2023-07-05 11:31 UTC, merged